import Combine
import Foundation
import SwiftUI

/// The user's chosen display language.
enum AppLanguage: String, CaseIterable, Identifiable, Codable, Sendable {
    case system = "system"
    case en = "en"
    case de = "de"
    case fr = "fr"
    case zhHans = "zh-Hans"

    var id: String { rawValue }

    var title: LocalizedStringKey {
        switch self {
        case .system: return "Follow System"
        case .en: return "English"
        case .de: return "Deutsch"
        case .fr: return "Français"
        case .zhHans: return "简体中文"
        }
    }

    var locale: Locale {
        switch self {
        case .system:
            return Locale.autoupdatingCurrent
        case .en:
            return Locale(identifier: "en")
        case .de:
            return Locale(identifier: "de")
        case .fr:
            return Locale(identifier: "fr")
        case .zhHans:
            return Locale(identifier: "zh-Hans")
        }
    }

    /// Languages whose strings were generated by an AI model rather than
    /// written by a person, and have not yet been reviewed by native speakers.
    /// Settings shows a notice for these so nobody mistakes them for reviewed
    /// work, and so people know where to send corrections. Remove a language
    /// from this set once a native speaker has been through it.
    static let machineTranslated: Set<AppLanguage> = [.de, .fr]

    /// The model that produced the machine translations, named in the notice.
    static let machineTranslationModel = "Claude Fable 5.1"

    /// The language a choice actually displays: the explicit pick, or for
    /// Follow System the language macOS resolved, if the app ships it.
    var effective: AppLanguage {
        guard self == .system else { return self }
        let code = Locale.autoupdatingCurrent.language.languageCode?.identifier ?? ""
        return AppLanguage(rawValue: code) ?? .en
    }

    var isMachineTranslated: Bool { AppLanguage.machineTranslated.contains(effective) }
}

/// Manages application-wide display language preference.
/// The UserDefaults key holding the chosen display language. Top level so the
/// non-isolated launch preflight below can read it without touching the
/// MainActor-bound manager.
let appLanguageDefaultsKey = "uk.co.bzwrd.macperfmonitor.language"

/// Applies the stored language choice to this process before anything reads
/// its localization. Writing `AppleLanguages` to the app's persistent
/// preferences steers `Locale` but, on current macOS, not the main bundle's
/// string-table selection, so a launch after switching language in Settings
/// would come up part-translated. The launch-argument domain is honored
/// everywhere, so `main()` calls this once before the SwiftUI lifecycle starts
/// and it places the choice there, exactly where `-AppleLanguages` on the
/// command line would put it.
///
/// This used to `execv` the binary with `-AppleLanguages` appended. On macOS 27
/// that replaced process keeps its pid but not its pid version, so MenuBarAgent
/// could not resolve it and the menu bar item never appeared whenever a
/// specific language was chosen (#124). Setting the argument domain in place
/// needs no second process.
enum AppLanguagePreflight {
    static func run() {
        guard !CommandLine.arguments.contains("-AppleLanguages"),
            let raw = UserDefaults.standard.string(forKey: appLanguageDefaultsKey),
            let language = AppLanguage(rawValue: raw), language != .system
        else { return }
        let defaults = UserDefaults.standard
        var arguments = defaults.volatileDomain(forName: UserDefaults.argumentDomain)
        arguments["AppleLanguages"] = [language.rawValue]
        defaults.setVolatileDomain(arguments, forName: UserDefaults.argumentDomain)
    }
}

@MainActor
final class AppLanguageManager: ObservableObject {
    static let languageDefaultsKey = appLanguageDefaultsKey

    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: Self.languageDefaultsKey)
            updateAppleLanguages()
        }
    }

    init() {
        let stored = UserDefaults.standard.string(forKey: Self.languageDefaultsKey)
        self.language = stored.flatMap(AppLanguage.init(rawValue:)) ?? .system
    }

    var currentLocale: Locale {
        language.locale
    }

    private func updateAppleLanguages() {
        // The raw value is the BCP 47 code macOS expects, so no per-language
        // table is needed and adding a language cannot miss this switch.
        if language == .system {
            UserDefaults.standard.removeObject(forKey: "AppleLanguages")
        } else {
            UserDefaults.standard.set([language.rawValue], forKey: "AppleLanguages")
        }
    }
}

/// Injects the active application locale into a view subtree dynamically.
struct LocaleRootView<Content: View>: View {
    @ObservedObject var languageManager: AppLanguageManager
    @ViewBuilder let content: () -> Content

    var body: some View {
        content()
            .environment(\.locale, languageManager.currentLocale)
            .environmentObject(languageManager)
    }
}
